### ISSUE TITLE
setKernelArgHostsideBuffer in src/hostside_opencl_funcs.cpp its 'documentation' mentions setKernelArgCharStar which no longer exists.

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/coriander#23]

**Comment by iame6162013** [comment]
I think setKernelArgCharStar had been renamed to setKernelArgGpuBuffer.

**Comment by hughperkins** [comment]
> I think setKernelArgCharStar had been renamed to setKernelArgGpuBuffer.

Yes, right :-)

**Comment by hughperkins** [comment]
Addressed in 7ecb04bfa . Thanks! :-)
