### ISSUE TITLE
Build failure for aarch64

### ISSUE THREAD

**Issue by JammyZhou** [hughperkins/coriander#28]
When tried to build coriander on my aarch64 board, I ran into some error below, and this conditional branch issue seems common for some other projects as well on aarch64.

[  2%] Built target clew
[  2%] Building CXX object CMakeFiles/clblast.dir/src/CLBlast/src/database/database.cpp.o

/tmp/ccitmCEV.s: Assembler messages:
/tmp/ccitmCEV.s:22989: Error: conditional branch out of range
/tmp/ccitmCEV.s:22996: Error: conditional branch out of range
CMakeFiles/clblast.dir/build.make:54: recipe for target 'CMakeFiles/clblast.dir/src/CLBlast/src/database/database.cpp.o' failed
make[2]: *** [CMakeFiles/clblast.dir/src/CLBlast/src/database/database.cpp.o] Error 1
CMakeFiles/Makefile2:1980: recipe for target 'CMakeFiles/clblast.dir/all' failed
make[1]: *** [CMakeFiles/clblast.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JammyZhou** [comment]
By the way, I'm using gcc 4.9.2.

**Comment by JammyZhou** [comment]
Never mind, the problem disappeared after I upgraded gcc/g++ to 6.3.0.

**Comment by hughperkins** [comment]
Good info, thanks! :-)
