### ISSUE TITLE
Error on python build script

### ISSUE THREAD

**Issue by MyForteIsTimeTravel** [hughperkins/coriander#38]
When running python install_distro.py on macOS Sierra 10.12.5 I get:

cd to [/Users/laptop/coriander]
cd to [/Users/laptop/coriander/soft]
wget --progress=dot:giga http://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz -O clang+llvm-4.0.0-x86_64-apple-darwin.tar.xz
Traceback (most recent call last):
  File "install_distro.py", line 193, in <module>
    main(**args.__dict__)
  File "install_distro.py", line 177, in main
    maybe_install_llvm(install_dir=install_dir)
  File "install_distro.py", line 138, in maybe_install_llvm
    install_llvm(install_dir)
  File "install_distro.py", line 113, in install_llvm
    run(['wget', '--progress=dot:giga', target_url, '-O', filename])
  File "install_distro.py", line 51, in run
    p = subprocess.Popen(cmdlist, cwd=current_dir, stdout=f_out, stderr=subprocess.STDOUT, bufsize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by hughperkins** [comment]
Thats odd. Can you check if you hav ea folder `/Users/laptop/coriander/soft`? If you dont, can you create it, and then retry?

**Comment by hughperkins** [comment]
By the way, can you clone into a different directory, ie not `~/coriadner`, but somewhere else, eg into `~/git`, and retry?

**Comment by hughperkins** [comment]
(I realize it's not very intuitive currently; and its different from how torch install works. I might fix that)

**Comment by MyForteIsTimeTravel** [comment]
I removed the folder, re-downloaded the repo to Documents and tried again, same issue I'm afraid. the soft directory does exists also. Any other ideas?

**Comment by hughperkins** [comment]
Oops.   Dont suppose... do you mind pulling down the latest version (I just updated it a bit), and try again pelase?

**Comment by MyForteIsTimeTravel** [comment]
RESOLVED, I didn't have wget installed. Don't think it comes as standard on macOS, curl is the usual alternative.

**Comment by hughperkins** [comment]
>RESOLVED, I didn't have wget installed. Don't think it comes as standard on macOS

oh, interesting. thanks! :-)

**Comment by hughperkins** [comment]
(addressed in https://github.com/hughperkins/coriander/commit/b24df27ae58db3e1cc6f6859234166a674f2eb9e )
