### ISSUE TITLE
Permission denied  (public key)

### ISSUE THREAD

**Issue by DarkTachyon** [hughperkins/coriander#39]
I don't know if it was a problem with shh (the internet I'm using has had problems) or something else, but I can't download the CLBlast submodule using the python install.
I've tried to manually download your CLBlast into the /src folder but it doesn't seem to notice it.

I am running Ubuntu 16.04

The exact errors are: 

/usr/bin/python /home/alex/coriander/bin/cocl_plugins.py install --repo-url https://github.com/hughperkins/coriander-clblast --git-branch master
Cloning into 'coriander-clblast'...
Cloning into 'src/CLBlast'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hughperkins/CLBlast' into submodule path 'src/CLBlast' failed
('CLANG_HOME', '/home/alex/coriander/soft/llvm-4.0')
('COCL_INSTALL_PREFIX', '/home/alex/coriander')
('COCL_INCLUDE', '/home/alex/coriander/include')
('COCL_LIB', '/home/alex/coriander/lib')
plugin_name [coriander-clblast]

Traceback (most recent call last):
  File "/home/alex/coriander/bin/cocl_plugins.py", line 114, in <module>
    func(**args_dict)
  File "/home/alex/coriander/bin/cocl_plugins.py", line 80, in install
    ], cwd=git_dir))
  File "/home/alex/coriander/bin/cocl_plugins.py", line 26, in check_output
    res = subprocess.check_output(cmdlist, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'clone', '--recursive', 'https://github.com/hughperkins/coriander-clblast', '-b', 'master', 'coriander-clblast']' returned non-zero exit status 128
p.returncode 1
Traceback (most recent call last):
  File "install_distro.py", line 221, in <module>
    main(**args.__dict__)
  File "install_distro.py", line 212, in main
    install_plugin(install_dir=install_dir, repo_url=repo_url, git_branch=git_branch)
  File "install_distro.py", line 199, in install_plugin
    '--git-branch', git_branch
  File "install_distro.py", line 88, in run
    assert p.returncode == 0
AssertionError

**Comment by hughperkins** [comment]
Thanks!  I've updated the url. can you retry please?

**Comment by DarkTachyon** [comment]
Yes, however I still had an error at the end. 

Traceback (most recent call last):
  File "/home/alex/coriander/bin/cocl_plugins.py", line 114, in <module>
    func(**args_dict)
  File "/home/alex/coriander/bin/cocl_plugins.py", line 92, in install
    ], cwd=build_dir))
  File "/home/alex/coriander/bin/cocl_plugins.py", line 26, in check_output
    res = subprocess.check_output(cmdlist, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['make', '-j', '8']' returned non-zero exit status 2
p.returncode 1
Traceback (most recent call last):
  File "install_distro.py", line 221, in <module>
    main(**args.__dict__)
  File "install_distro.py", line 212, in main
    install_plugin(install_dir=install_dir, repo_url=repo_url, git_branch=git_branch)
  File "install_distro.py", line 199, in install_plugin
    '--git-branch', git_branch
  File "install_distro.py", line 88, in run
    assert p.returncode == 0
AssertionError


Or is this normal?

**Comment by hughperkins** [comment]
No, that doesnt seem normal... What output do you get if you do:
```
cd ~/coriander/git/coriander-clblast/build/
make
```

**Comment by DarkTachyon** [comment]
[ 96%] Built target clblast
[100%] Built target corianderclblast

**Comment by hughperkins** [comment]
wierd. waht about:
```
cd ~/coriander/git/coriander-clblast/build/
make -j 8
```
?

**Comment by hughperkins** [comment]
If that still works, waht bout, well, can you purge the folder, and redo the cocl_plugins.py command? :
```
rm -Rf ~/coriander/git/coriander-clblast
cocl_plugins.py install --repo-url https://github.com/hughperkins/coriander-clblast --git-branch master
```
And paste the entire output, including the command itself, into a https://gist.github.com ?

Thank yo ufor your help with this :-)

**Comment by DarkTachyon** [comment]
I'm assuming you meant to have the python command before.
https://gist.github.com/DarkTachyon/223fa849c54c7b818005e74d8858ea24

**Comment by hughperkins** [comment]
> I'm assuming you meant to have the python command before.

Yes :-)

> https://gist.github.com/DarkTachyon/223fa849c54c7b818005e74d8858ea24

Hmmm. Seems all is good now in fact?

**Comment by DarkTachyon** [comment]
Yeah, just now my smoke test has a seg fault xD

https://gist.github.com/DarkTachyon/ec7654d19a5c27c012c453b430e826fd

**Comment by hughperkins** [comment]
Ok. Can you open that as a new issue?  I dont have time to look at that at the moment though, so you might need to poke around a bit yourself...
