### ISSUE TITLE
cuSolver support

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/coriander#52]
AFAIK there isn't any support in coriander for cuSolver, are there any plans to support cuSolver?

I assume this should be done through a plugin like Coriander-dnn, is this a difficult process?

**Comment by hughperkins** [comment]
I'm not planning on adding cuSolver myself. However, does sound like an interesting project.

You'd need to either write your own solver in OpenCL (eg Cholesky), or else find an existing OpenCL implementation. The former sounds like more fun to be honest :) but if there is an existing implementation, that existing implementation might be already highly optimized, and portable.

**Comment by iame6162013** [comment]
I'll see what I can do. I'm not yet to experienced, so I'll think I'll use an external lib. No need to reinvent the wheel.
