### ISSUE TITLE
[...] Eigen is a pre-requisite for running Eigen.

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/coriander#53]
In: coriander/test/eigen/README.md
We see the following sentence:

> Eigen is used by Tensorflow, so being able to build and run Eigen is a pre-requisite for running Eigen.

Surely you mean:

> Eigen is used by Tensorflow, so being able to build and run Eigen is a pre-requisite for running Tensorflow.

If you want me to make a PR for it, ask me. :)

**Comment by hughperkins** [comment]
Yes, you are right that it should be `Tensorflw`, and not `Eigen` :)
