### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MohamedWagih96** [hughperkins/coriander#73]
On running install_distro.py script i get this error
<pre>exception: [Errno 2] No such file or directory
current_dir [/home/rogue/coriander/soft]
cmdlist [&apos;curl&apos;, &apos;http://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz&apos;, &apos;-o&apos;, &apos;clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz&apos;]
</pre>

I'm using ubuntu 18.04

**Comment by imsrgadich** [comment]
@MohamedWagih96 how did you solve it?

**Comment by MohamedWagih96** [comment]
Well, I can't remember correctly but here's two thing i might have done:
1- 
![image](https://user-images.githubusercontent.com/30757576/50541842-f0000f80-0bb6-11e9-88a4-0b76c4d223aa.png)

Do this step before running the script 

2- Update CLang/LLVM , or update the OS generally
Unfortunately I'm not working on Ubuntu anymore so I can't really try again for you
Keep me updated after you try these two steps

**Comment by imsrgadich** [comment]
@MohamedWagih96  hey, thank you for your reply. I was trying to run PyTorch using this but it seems you can't. So I'm dropping this. thanks!
