### ISSUE TITLE
MacOS installation error [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by imsrgadich** [hughperkins/coriander#81]
Hi,

Can someone help me with this error? Thank you. 

```
exception: [Errno 2] No such file or directory
current_dir [./build]
cmdlist ['cmake', '..', '-DCLANG_HOME=/Users/imsrgadich/coriander/soft/llvm-4.0', '-DCMAKE_INSTALL_PREFIX=/Users/imsrgadich/coriander']
```

I'm on `MacBook Pro (Retina, 15-inch, Mid 2015, MacOS 10.14.1)` with GPU `AMD Radeon R9 M370X` with `OpenCL 1.2`.

I'm trying to run PyTorch on AMD GPU, is this feasible by using Coriander? Thank you.

**Comment by imsrgadich** [comment]
The problem is with `subprocess.Popen` for `install_coriander` definition. I cannot understand what the error is.

**Comment by hughperkins** [comment]
Pytorch won't work with coriander currently.

**Comment by imsrgadich** [comment]
Thank you for the reply. :)
